Hw1
lloppy/java-course-tinkoff pull request #1
Opened 2023-10-09 19:06 UTC by lloppy

2023-10-10 16:55 UTC, kkkoltunov commented
привет, я твой ассистент на курсе, если что со мной можно на ты))

обрати внимание, у тебя не проходит проверка код стайла, это необходимо исправить https://github.com/lloppy/java-course-tinkoff/actions/runs/6460725769/job/17538985268?pr=1

2023-10-10 17:04 UTC, kkkoltunov requested changes
Хорошая работа, молодец! Оставил небольшие замечания, поправь их пожалуйста

2023-10-10 17:04 UTC, kkkoltunov commented on src/main/java/edu/hw1/Task1.java
> +        int minutes = Integer.parseInt(time[0]);
а что будет если нам придут не числа, а `abc:abc`? давай обработаем этот кейс как ошибочный и напишем тест

2023-10-10 17:04 UTC, kkkoltunov commented on src/main/java/edu/hw1/Task4.java
> +            fixedString += brokenString.charAt(i + 1);
обращай внимание на ворнинги, конкатенацию лучше не использовать в джаве вообще, тк каждый раз строчка будет пересоздаваться, а память не бесконечная, давай воспользуемся `StringBuilder`

https://www.baeldung.com/java-strings-concatenation
https://stackoverflow.com/questions/3835806/is-it-always-a-bad-idea-to-use-to-concatenate-strings

2023-10-10 17:04 UTC, kkkoltunov commented on src/main/java/edu/hw1/Task6.java
> +        return difference;
можно сразу сделать так 
```
return Integer.parseInt(descending) - Integer.parseInt(ascending);
```

2023-10-10 17:04 UTC, kkkoltunov commented on src/test/java/edu/hw1/Task1Test.java
> +    void minutesToSeconds_sec() {
давай писать названия тестов в camelCase без нижних подчеркиваний в формате `testThat...Returned...`

2023-10-11 09:32 UTC, lloppy commented on src/test/java/edu/hw1/Task1Test.java
> +    void minutesToSeconds_sec() {
Спасибо, всё исправила

2023-10-11 17:10 UTC, kkkoltunov commented
все огонь! ты видимо еще должна мне дать какой-то доступ чтобы я мог резролвить треды, видимо выше доступ чем тот который есть у меня сейчас, сделай это пожалуйста чтобы при проверке следующих работ было проще работать, и еще старайся отписывааться в комментах что ты поправила, что не поправила, возможно с чем-то не согласна, со мной можно и нужно спорить

2023-10-11 18:43 UTC, lloppy commented
> все огонь! ты видимо еще должна мне дать какой-то доступ чтобы я мог резролвить треды, видимо выше доступ чем тот который есть у меня сейчас, сделай это пожалуйста чтобы при проверке следующих работ было проще работать, и еще старайся отписывааться в комментах что ты поправила, что не поправила, возможно с чем-то не согласна, со мной можно и нужно спорить

Отправила заявку на доступ, скорее всего лежит на почте. 
Про обсуждение решений - поняла)) 

Мержить в мейн ветку должна я? В инструкции написано только : После выставления оценки PR сливается в основную ветку (https://edu.tinkoff.ru/my-activities/courses/stream/15714531-b1bc-45de-874a-af94e7d5a21c/unit/14d76576-8ece-484b-9ffa-118ca3ab2e8f)

2023-10-15 16:24 UTC, merged