Hw2
lloppy/java-course-tinkoff pull request #2
Opened 2023-10-15 22:01 UTC by lloppy

2023-10-19 17:58 UTC, kkkoltunov commented
кинь еще раз пожалуйста инват в коллабораторы и напиши в тг мне как это сделаешь @kkkoltunov 

я не успел его принять(

2023-10-19 18:30 UTC, kkkoltunov requested changes
молодец! все круто! пока одни из самых сильных работа на курсе, приятно проверять, продолжай в том же духе

поправь плиз замечания и зачтем домашку

2023-10-19 18:30 UTC, kkkoltunov commented on src/test/java/edu/hw2/Task1Test.java
> +        var two = new Constant(2);
давай стараться свести к минимуму использование var в коде, это сильно усложняет его читаемость

почитай статью https://habr.com/ru/articles/346214/, в var есть плюсы, но например в циклах, в продакшен коде у нас таких конструкций единицы, стоит поправить **везде**

2023-10-19 18:30 UTC, kkkoltunov commented on src/test/java/edu/hw2/Task1Test.java
> +        assertEquals(2.0, two.evaluate(), 1e-10);
дельту тоже можно вынести в константы всего тестового класса

2023-10-19 18:30 UTC, kkkoltunov commented on src/test/java/edu/hw2/Task1Test.java
> +        var mult = new Multiplication(sumTwoFour, negOne);
старайся не урезать названия переменным, чтобы было легче читать
```
        var multiplication = new Multiplication(sumTwoFour, negOne);
```

2023-10-19 18:30 UTC, kkkoltunov commented on src/main/java/edu/hw2/Task1.java
> +public final class Task1 {
давай тогда заодно и эти тестовые классы запихнем в пакеты task1 и task2 соответсвенно, то что там будет лежать по одному классу - не страшно

2023-10-19 18:30 UTC, kkkoltunov commented on src/test/java/edu/hw2/Task2Test.java
> +
лишние пробелы, давай уберем

2023-10-19 18:30 UTC, kkkoltunov commented on src/main/java/edu/hw2/Task2.java
> +        private double width;
к приватным неизменяемым полям добавляем ключевое слово final 
```
        private final double height;
        private final double width;
```

2023-10-19 18:30 UTC, kkkoltunov commented on src/main/java/edu/hw2/Task2.java
> +        private double side;
здесь тоже final

2023-10-19 18:30 UTC, kkkoltunov commented on src/test/java/edu/hw2/Task2Test.java
> +    void rectangleArea(Shape rect) {
поправь **везде** сокращенные переменные на полное название

2023-10-19 18:30 UTC, kkkoltunov commented on src/main/java/edu/hw2/task3/README.md
> +#### Схема - https://mm.tt/app/map/2988750588?t=cf90Aku2P0
за это конечно отдельный респект))

жаль что не могу поставить доп баллы

2023-10-20 10:31 UTC, lloppy commented
> молодец! все круто! пока одни из самых сильных работа на курсе, приятно проверять, продолжай в том же духе
> 
> поправь плиз замечания и зачтем домашку

Спасибо! Поправила)

2023-10-25 13:02 UTC, kkkoltunov commented
после того как доработала отправляй пожалуйста работу на сдачу заново через платорму edu, тк я не слежу за уведмолениями гитхаба я не могу отследить правки

2023-10-25 13:03 UTC, kkkoltunov commented
можно мерджить все ок

2023-10-25 13:07 UTC, merged